name: Build Mod

on: [push, pull_request, workflow_dispatch]

jobs:
  buildJar:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up PATH
        run: |
          echo "${ANDROID_HOME}/build-tools/34.0.0" >> $GITHUB_PATH

      - name: Set up JDK 25
        uses: actions/setup-java@v1
        with:
          java-version: 25

      - name: Build mod jar
        run: |
          chmod +x ./gradlew
          ./gradlew deploy

      - name: Upload built jar file
        uses: actions/upload-artifact@v4
        with:
          name: opendustry-build
          path: build/libs/*.jar
